Basic game functionality
orsa-scholis/orsum-inflandi pull request #70
Opened 2019-04-22 17:06 UTC by TheFehr

- [ ] incoming message validation

- [ ] game listing

- [ ] game join

- [ ] game setStone

2019-05-06 14:10 UTC, lukasbischof commented on backend/client.go
> +
This is empty

2019-05-06 14:37 UTC, skius requested changes

2019-05-06 14:37 UTC, skius commented on backend/client.go
> +
I agree

2019-05-06 14:38 UTC, lukasbischof requested changes
Please implement @skius changes

2019-05-06 14:38 UTC, skius approved these changes
About the _slice_

2019-05-06 14:38 UTC, skius commented on backend/client.go
> +func validateMessage(received message, expected message) (errs []error) {
Great idea, return value as []error

2019-07-18 06:48 UTC, lukasbischof requested changes

2019-07-18 06:48 UTC, lukasbischof commented on backend/server/player.go
> +	user = &Types.User{ugins
What's an `ugin`?

2019-08-20 11:02 UTC, closed without merging