Feature Client Sending Communication
orsa-scholis/orsum-inflandi pull request #99
Opened 2019-05-20 21:13 UTC by lukasbischof

2019-05-20 21:17 UTC, lukasbischof commented on frontend/src/containers/LobbyScreen/LobbyScreen.tsx
> +    void connection.send(new Message(Protocol.ClientCommands.CONNECTION.CONNECT, user));
For debögging

2019-05-21 06:31 UTC, TheFehr commented on frontend/src/connection/proto/ProtoPayload.ts
> +export type ProtoPayload = User | GameRequest | Game | GameList | FourInARowTurnPayload | ChatMessage | GameEnd;
Shouldn't FourInARowTurnPayload be just Turn

2019-05-21 06:35 UTC, TheFehr requested changes
See my comment in ProtoPayload.ts

2019-05-21 06:46 UTC, TheFehr approved these changes
I like

2019-05-21 06:47 UTC, merged